apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo
  labels:
    release: demo
spec:
  selector:
    matchLabels:
      app: demo
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: {{ .Values.appName }}
    path: /actuator/prometheus
    

