apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels: 
    app: demo
    app.kubernetes.io/name: kube-prometheus
spec:
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer
  ports:
    - name: {{ .Values.appName }}
      port: 8080
      targetPort: 8080
      protocol: TCP
  serviceAccountName: 
