apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-service
  labels:
    app: demo-service
spec:
  selector:
    matchLabels:
      app: demo-service
  replicas: 2
  template:
    metadata:
      name: demo-service
      labels:
        app: demo-service
    spec:
      containers:
        - name: demo-service
          image: "matheuscruzdev/demo"