apiVersion: v1
kind: Service
metadata:
  name: demo-service-svc
spec:
  selector:
    app: demo-service
  type: LoadBalancer
  ports:
    - name: demo-service-svc
      port: 8080
      targetPort: 8080
      protocol: TCP